elsa/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from main import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^accounts/', include('friends.urls')),
    url(r'^context/', include('context.urls')),
    url(r'^build/', include('build.urls')),
    url(r'^review/', include('review.urls')),
    url(r'^tutorial/', include('tutorial.urls')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static(settings.ARCHIVE_URL, document_root=settings.ARCHIVE_DIR)

friends/urls.py
from django.conf.urls import url
from . import views



app_name='friends'
urlpatterns = [
    #url(r'^$', views.FriendList.as_view(), name='friends'),
    url(r'^(?P<pk_user>\d+)/$', views.profile, name='profile'),
    url(r'^login/$', views.friend_login, name='login'),
    url(r'^logout/$', views.friend_logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<pk_user>\d+)/settings/$', views.friend_settings, name='settings'),

]

main/urls.py
"""
K. Sweebe

elsa.main.urls shows the listing of all current urls associated with elsa's main app.

"""

from django.conf.urls import url
from . import views

app_name='main'
urlpatterns = [

    # elsa's main views.
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^services/$', views.services, name='services'),
    url(r'^construction/$', views.construction, name='construction'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^error/$', views.error, name='error'),
    url(r'^restricted_access/$', views.restricted_access, name='restricted_access'),
    url(r'^simple_upload/$', views.simple_upload, name='simple_upload'),

    # I use this for development (k).
    url(r'^success/$', views.success, name='success'),
]

review/urls.py
from django.conf.urls import url
from . import views



app_name='review'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
#from build.models import Bundle

def get_user_document_directory(instance, filename):
    
    document_collection_directory = 'archive/{0}/{1}/documents/'.format(instance.bundle.user.username, instance.bundle.name)
    return document_collection_directory

# Create your models here.
@python_2_unicode_compatible
class Joke(models.Model):
    question = models.CharField(max_length=500, unique=True, default="")
    answer = models.CharField(max_length=500, default="")    
    likes = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Joke'
        verbose_name_plural = 'Jokes'

    def __str__(self):
        return self.question

@python_2_unicode_compatible
class UploadedDocument(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to=get_user_document_directory)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description

    

main/forms.py
from django import forms
from .models import UploadedDocument

class ContactForm(forms.Form):

    name = forms.CharField()
    email = forms.CharField()
    agency = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)


class UserContactForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea)


class UploadedDocumentForm(forms.ModelForm):
    class Meta:
        model = UploadedDocument
        fields = ('description', 'document',)

main/views.py
"""
K. Sweebe

elsa.main.views contains all of the views responsible for the main core of elsa.  This includes elsa's homepage, contact information for elsa, a service's page that details all of the various apps in elsa, and other views listed below.  

To decide if a view belongs in elsa.main.views, ask yourself one of two questions:
	1. Does the view pertain specifically to elsa and not to another app?
	2. Is the view one that could be used in multiple apps?

If you said yes to either, then the view belongs in elsa.main.views.

"""






# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import EmailMessage
from django.shortcuts import render
from django.template.loader import get_template
from .models import Joke
from .forms import ContactForm, UserContactForm, UploadedDocumentForm # I'm not sure uploaded document form should be here (k).
import random
import os
import logging  # This document logs errors and is currently not in use in ELSA.  Feel free to develop this (k).
from datetime import date

#logger = loggin.getLogger(__name__)



# Create your views here.

# index is the home page for elsa.
def index(request):
    return render(request, 'main/index.html', {})

# about describes elsa's purpose, goal, etc.
def about(request):
    return render(request, 'main/about.html', {})

# contact provides a means for users to contact atmos through contact cards and direct email to elsa@nmsu.edu.
def contact(request):
    contact_form = ContactForm(request.POST or None)
    user_contact_form = UserContactForm(request.POST or None)
    context_dict = {}
    context_dict['contact_form'] = contact_form
    context_dict['user_contact_form'] = user_contact_form
    context_dict['email_sent'] = False
    context_dict['user_logged_in'] = False
    template = get_template('main/contact_template.txt')
           
    if request.user.is_authenticated():
        context_dict['user_logged_in'] = True
        if user_contact_form.is_valid():
            print 'user_contact_form is valid'
           
            context_dict['name'] = '{0}, {1}'.format(request.user.last_name, request.user.first_name)
            context_dict['email'] = request.user.email
            context_dict['agency'] = request.user.userprofile.agency
            context_dict['message'] = user_contact_form.cleaned_data['message']
            content = template.render(context_dict)
            email = EmailMessage(
                subject = "{} is contacting ELSA".format(context_dict['name']),
                body = content,
                from_email = context_dict['email'],
                to = ['elsa@atmos.nmsu.edu',],
                headers = {'Reply-To': context_dict['email'] }
            )
            email.send()
            context_dict['email_sent'] = True

        #else:
         #   logger.error('{}: user_contact_form is not valid'.format(date.today()))

    else:
        if contact_form.is_valid():
            print 'contact_form is valid'

            # Email the profile with the contact information
            context_dict['name'] = contact_form.cleaned_data['name']
            context_dict['email'] = contact_form.cleaned_data['email']
            context_dict['agency'] = contact_form.cleaned_data['agency']
            context_dict['message'] = contact_form.cleaned_data['message']
            content = template.render(context_dict)
            email = EmailMessage(
                subject = "{} is contacting ELSA".format(context_dict['name']),
                body = content,
                from_email = context_dict['email'],
                to = ['elsa@atmos.nmsu.edu',],
                headers = {'Reply-To': context_dict['email'] }
            )
            email.send()
            context_dict['email_sent'] = True

        #else:
            #logger.error('{}: contact_form is not valid.'.format(datetime.now()))

    return render(request, 'main/contact.html', context_dict)

# restricted_access is the page that displays if a user is travelling to an area they have no business being in.
@login_required
def restricted_access(request):
    return render(request, 'main/restricted_access.html', {})


# services displays the various apps encompassed by elsa.
@login_required
def services(request):
    return render(request, 'main/services.html', {})


# this is a simple_upload view used to upload a document.  I have no idea why this is here other than that I used it to upload a document at some point in time.  I should really comment more (k).
@login_required
def simple_upload(request):
    context_dict = {}
    if request.method =='POST':
        form = UploadedDocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = UploadedDocumentForm()
    context_dict['form'] = form
    return render(request, 'main/simple_upload.html', context_dict)


# anytime a page is under construction, we use this view.
@login_required
def construction(request):
    return render(request, 'main/construction.html', {})


# ------ TEST VIEWS -------

def error(request):
    random_index = random.randint(0, Joke.objects.count()-1)
    random_joke = Joke.objects.all()[random_index]
    return render(request, 'main/error.html', {'random_joke':random_joke})


def success(request):
    return render(request, 'main/success.html')

templates/main/base-k.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>ELSA: {% block title_block %}Educational Labeling System @Atmospheres{% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/elsa-help.css' %}" rel="stylesheet">
    <link href="{% static 'css/elsa-tutorial.css' %}" rel="stylesheet">
    <link href="{% static 'css/elsa-new.css' %}" rel="stylesheet">
    <!--<link href="{% static 'css/elsa-todo.css' %}" rel="stylesheet">-->
</head>

<body>

    <!-- Start your project here-->
    <header>

        <!--Navbar-->
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark elegant-color-dark">

            <!-- Navbar brand -->
            <a class="navbar-brand" href="{% url 'main:index' %}">
                <i id="icon" class="fa fa-snowflake-o" style="text-shadow: none; font-size: 25px; color: rgb(43, 187, 173); height: 30px; width: 30px; line-height: 30px; border-radius: ; text-align: center; background-color: rgb(46, 46, 46);"></i> 
                ELSA
             </a>

            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:about' %}"><i class="fa fa-snowflake-o" aria-hidden="true"></i> About</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:services' %}"><i class="fa fa-briefcase"></i> Bundle Apps</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contact' %}"><i class="fa fa-envelope"></i> Contact</a>
                    </li>

                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> {{ user }}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{{ user.userprofile.get_absolute_url }}">{{ user.first_name }}'s Profile</a>
                            <a class="dropdown-item" href="{% url 'main:construction' %}">Profile Settings</a>
                            <a class="dropdown-item" href="{% url 'friends:logout' %}">Logout</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'friends:register' %}"><i class="fa fa-hand-spock-o" aria-hidden="true"></i> Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'friends:login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contact' %}"><i class="fa fa-envelope"></i> Contact</a>
                    </li>
                    {% endif %}

                </ul>
                <!-- Links -->

            </div>
            <!-- Collapsible content -->
            <!-- Navbar brand -->
            <a href="{% url 'main:index' %}">
                <img src="{% static 'images/PDS_Planets.png' %}" style="text-shadow: none; font-size: 25px; color: rgb(43, 187, 173); height: 50px; width: 95px; line-height: 75px; border-radius: ; text-align: center; "></i> 
                
             </a>

        </nav>
        <!--/.Navbar-->              
    </header>
    <!--/.Header-->

<!-- TO DO LIST IS... AS DANAE WOULD SAY, JANKY!!  Fix before show!!
    <aside>
        <!--To do list
        <div id="mySidenav" class="sidenav">

 <div id="myDIV" class="header">
  <h2>My To Do List</h2>
  <input type="text" id="myInput" placeholder="Title...">
  <span onclick="newElement()" class="addBtn">Add</span>
</div>

<ul id="myUL">
  <li>Hit the gym</li>
  <li class="checked">Pay bills</li>
  <li>Meet George</li>
  <li>Buy eggs</li>
  <li>Read a book</li>
  <li>Organize office</li>
</ul> 

          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        </div>

        <div id="main">  
          <br/><br/><br/><br/>        
          <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; to-do</span>
        </div>

        <!--/.To do list
    </aside>
-->


    <!--Main-->
    <main class="mt-5">
        <div class="container">

            <div class="d-flex justify-content-center">
                <div class="container">


<!--Section: Blog v.3-->
<section class="section extra-margins pb-3 text-center text-lg-left">

    <!--Section heading-->
    <h2 class="section-heading h1 pt-4">{% block main_header_block %}{% endblock %}</h2>
    <!--Section description-->
    <p class="section-description">{% block about_header_block %}{% endblock %}</p>
    <!--SPOT FOR EXERCISE FOUND IN about_templates.txt-->


</section>
<!--Section: Blog v.3-->
                    <!--Body block-->
                    {% block body_block %}
                    {% endblock %}
                    <!--/.Body block-->
                </div>
            </div>
        </div>
    </main>
    <!--/.Main-->


    <!--Footer-->
    <footer class="page-footer elegant-color center-on-small-only"> <!-- fixed-bottom class-->

        <!--Footer Links-->
        <div class="container">
            <div class="row">

                <!--First column-->
                <div class="col-md-6">
                    <a href="{% url 'main:index' %}">
                    <h6 class="title">
 <i id="icon" class="fa fa-snowflake-o" style="text-shadow: rgb(32, 32, 32) 0px 0px 0px, rgb(33, 33, 33) 1px 1px 0px, rgb(34, 34, 34) 2px 2px 0px, rgb(35, 35, 35) 3px 3px 0px, rgb(35, 35, 35) 4px 4px 0px, rgb(36, 36, 36) 5px 5px 0px, rgb(37, 37, 37) 6px 6px 0px, rgb(38, 38, 38) 7px 7px 0px, rgb(38, 38, 38) 8px 8px 0px, rgb(39, 39, 39) 9px 9px 0px, rgb(40, 40, 40) 10px 10px 0px, rgb(41, 41, 41) 11px 11px 0px, rgb(41, 41, 41) 12px 12px 0px, rgb(42, 42, 42) 13px 13px 0px, rgb(43, 43, 43) 14px 14px 0px, rgb(44, 44, 44) 15px 15px 0px, rgb(44, 44, 44) 16px 16px 0px, rgb(45, 45, 45) 17px 17px 0px; font-size: 50px; color: rgb(43, 187, 173); height: 107px; width: 107px; line-height: 107px; border-radius: ; text-align: center; background-color: rgb(46, 46, 46);"></i> 
                    Educational Labeling System @Atmospheres
                    </a>
                    </h6>
                </div>
                <!--/.First column-->



                <!--Second column-->

                <div class="col-md-6">
                    <h6 class="title">
                    <a href="http://atmos.nmsu.edu/">
 
 <i id="icon" class="fa fa-cloud" style="text-shadow: rgb(32, 32, 32) 0px 0px 0px, rgb(33, 33, 33) 1px 1px 0px, rgb(34, 34, 34) 2px 2px 0px, rgb(35, 35, 35) 3px 3px 0px, rgb(35, 35, 35) 4px 4px 0px, rgb(36, 36, 36) 5px 5px 0px, rgb(37, 37, 37) 6px 6px 0px, rgb(38, 38, 38) 7px 7px 0px, rgb(38, 38, 38) 8px 8px 0px, rgb(39, 39, 39) 9px 9px 0px, rgb(40, 40, 40) 10px 10px 0px, rgb(41, 41, 41) 11px 11px 0px, rgb(41, 41, 41) 12px 12px 0px, rgb(42, 42, 42) 13px 13px 0px, rgb(43, 43, 43) 14px 14px 0px, rgb(44, 44, 44) 15px 15px 0px, rgb(44, 44, 44) 16px 16px 0px, rgb(45, 45, 45) 17px 17px 0px; font-size: 50px; color: rgb(43, 187, 173); height: 107px; width: 107px; line-height: 107px; border-radius: ; text-align: center; background-color: rgb(46, 46, 46);"></i> 
                    Planetary Atmospheres Node
                    </a>
                    </h6>
                </div>
                <!--/.Second column-->
            </div>
        </div>
        <!--/.Footer Links-->

        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container">
                © Not Copyrighted But Don't Steal Me: <a href="{% url 'main:index' %}"> https://atmos.nmsu.edu/elsa/ </a>
            </div>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

    <!-- /Start your project here-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- ELSA JavaScript -->
    <script type="text/javascript" src="{% static 'js/elsa-help.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/elsa-new.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/elsa-tutorial.js' %}"></script>
    <!--<script type="text/javascript" src="{% static 'js/elsa-todo.js' %}"></script>-->
    <!-- Font Awesome -->
    <script src="https://use.fontawesome.com/dc496c8662.js"></script>

</body>

</html>

templates/main/index.html
{% extends 'main/base-k.html' %}
{% load staticfiles %}

{% block main_header_block%}
Welcome to <span class="text-muted">ELSA</span>.<hr/>
{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
        <!--Row-->
        <div class="row pt-2">
            <!--Column-->
            <div class="col-md-12">    
                <!--Panel-->
                <div class="card">
                    <!--Header-->
                    <h3 class="card-header elegant-color white-text text-center z-depth-2">
                    What does ELSA do?
                    </h3>
                    <!--/.Header-->
                    <!--Body-->
                    <div class="card-body">
                        <br/>
                        <h4 class="card-title">Take a walk with ELSA, {{ user.first_name }}.</h4>
                        <p class="card-text">ELSA is a user-centered application that aids in the creation of PDS4 compliant labels for your data bundles.  Since ELSA is a user-centered application, let's first take you to your profile page.  {k}.</p>
                        <center><a class="btn btn-default" href="{{ user.userprofile.get_absolute_url }}">@{{ user }}</a></center>
                    </div>
                    <!--/.Body-->
                </div>
                <!--/.Panel-->
            </div>
            <!--/.Column-->
        </div>
        <!--/.Row-->
        <hr/>
        <!--Row -->
        <div class="row pt-2">
            <!--Column-->
            <div class="col-md-12">    
                <!--Panel-->
                <div class="card">
                    <!--Header-->
                    <h3 class="card-header elegant-color white-text text-center z-depth-2">
                    Who is ELSA for?
                    </h3>
                    <!--/.Header-->
                    <!--Body-->
                    <div class="card-body">
                        <br/>
                        <h4 class="card-title">Are you part of the PDS4 community?</h4>
                        <p class="card-text">ELSA was created to help lessen the learning curve involved for new PDS4 users.  Check out the Planetary Data System's page to learn more about data archiving and distribution.</p>
                        <center><a class="btn btn-default" href="https://pds.jpl.nasa.gov/">@PDS4.</a></center>
                    </div>
                    <!--/.Body-->
                </div>
                <!--/.Panel-->
            </div>
            <!--/.Column-->
        </div>
        <!--/.Row-->
        <hr/>
        <!--Row -->
        <div class="row pt-2">
            <!--Column-->
            <div class="col-md-12">    
                <!--Panel-->
                <div class="card">
                    <!--Header-->
                    <h3 class="card-header elegant-color white-text text-center z-depth-2">
                    Why ELSA?
                    </h3>
                    <!--/.Header-->
                    <!--Body-->
                    <div class="card-body">
                        <br/>
                        <h4 class="card-title">Well, ELSA is great!</h4>
                        <p class="card-text">ELSA is an educational tool.  ELSA is currently in development but is making pretty good progress.  You can read more about ELSA below.</p>
                        <center><a class="btn btn-default" href="{% url 'main:about' %}">@ABOUT.</a></center>
                    </div>
                    <!--/.Body-->
                </div>
                <!--/.Panel-->
            </div>
            <!--/.Column-->
        </div>
        <!--/.Row-->
        <hr/>


        
    {% else %}
        <!--Row-->
        <div class="row pt-2">
            <!--Column-->
            <div class="col-md-12">
                <p>The Educational Labeling System @Atmospheres (ELSA) is a tool designed to help streamline the creation of PDS4 compliant labels.  Here at Atmos we believe in taking a top-down approach when it comes to your data.  ELSA begins with the unique name of your bundle, trickles down through your collections, and ends with the details of your data to provide you with PDS4 labels.</p>
           </div>
           <!--/.Column-->
       </div>
       <!--/.Row-->
       <hr/>
       <!--Row-->
       <div class="row pt-2">
           <!--Column-->
           <div class="col-md-7 push-md-5">
              <p class="lead"> 
                  <a href="{% url 'friends:register' %}">
                      <center><button class="btn btn-default">
                     Sign Up Here
                      </button></center>
                  </a>
                  <br/>
                  <form id="login_form" method="post" action="{% url 'friends:login' %}">
                      {% csrf_token %}
                      Username:  <input type="text" name="username" value="" size="50" /><br />
                      Password:  <input type="password" name="password" value="" size="50"/><br />
                  <center><input class="btn btn-default" type="submit" value="login" /></center>
                  </form>
              </p>
          </div>
          <!--/.Column-->
      </div>
      <!--/.Row-->
    {% endif %}
{% endblock %}


<!--SPOT FOR EXERCISE FOUND IN about_templates.txt-->

templates/main/index2018.html
{% extends 'main/base-k.html' %}
{% load staticfiles %}

{% block main_header_block%}
Welcome to <span class="text-muted">ELSA</span>.<hr/>
{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
        <!--Row-->
        <div class="row pt-2">
            <!--Column-->
            <div class="col-md-12">    
                <!--Panel-->
                <div class="card">
                    <!--Header-->
                    <h3 class="card-header elegant-color white-text text-center z-depth-2">
                    What does ELSA do?
                    </h3>
                    <!--/.Header-->
                    <!--Body-->
                    <div class="card-body">
                        <br/>
                        <h4 class="card-title">Take a walk with ELSA, {{ user.first_name }}.</h4>
                        <p class="card-text">ELSA is a user-centered application that aids in the creation of PDS4 compliant labels for your data bundles.  Since ELSA is a user-centered application, let's first take you to your profile page.  {k}.</p>
                        <center><a class="btn btn-default" href="{{ user.userprofile.get_absolute_url }}">@{{ user }}</a></center>
                    </div>
                    <!--/.Body-->
                </div>
                <!--/.Panel-->
            </div>
            <!--/.Column-->
        </div>
        <!--/.Row-->
        <hr/>
        <!--Row -->
        <div class="row pt-2">
            <!--Column-->
            <div class="col-md-12">    
                <!--Panel-->
                <div class="card">
                    <!--Header-->
                    <h3 class="card-header elegant-color white-text text-center z-depth-2">
                    Who is ELSA for?
                    </h3>
                    <!--/.Header-->
                    <!--Body-->
                    <div class="card-body">
                        <br/>
                        <h4 class="card-title">Are you part of the PDS4 community?</h4>
                        <p class="card-text">ELSA was created to help lessen the learning curve involved for new PDS4 users.  Check out the Planetary Data System's page to learn more about data archiving and distribution.</p>
                        <center><a class="btn btn-default" href="https://pds.jpl.nasa.gov/">@PDS4.</a></center>
                    </div>
                    <!--/.Body-->
                </div>
                <!--/.Panel-->
            </div>
            <!--/.Column-->
        </div>
        <!--/.Row-->
        <hr/>
        <!--Row -->
        <div class="row pt-2">
            <!--Column-->
            <div class="col-md-12">    
                <!--Panel-->
                <div class="card">
                    <!--Header-->
                    <h3 class="card-header elegant-color white-text text-center z-depth-2">
                    Why ELSA?
                    </h3>
                    <!--/.Header-->
                    <!--Body-->
                    <div class="card-body">
                        <br/>
                        <h4 class="card-title">Well, ELSA is great!</h4>
                        <p class="card-text">ELSA is an educational tool.  ELSA is currently in development but is making pretty good progress.  You can read more about ELSA below.</p>
                        <center><a class="btn btn-default" href="{% url 'main:about' %}">@ABOUT.</a></center>
                    </div>
                    <!--/.Body-->
                </div>
                <!--/.Panel-->
            </div>
            <!--/.Column-->
        </div>
        <!--/.Row-->
        <hr/>


        
    {% else %}
        <!--Row-->
        <div class="row pt-2">
            <!--Column-->
            <div class="col-md-8">
                <p>The Educational Labeling System @Atmospheres (ELSA) is a tool designed to help streamline the creation of PDS4 compliant labels.  Here at Atmos we believe in taking a top-down approach when it comes to your data.  ELSA begins with the unique name of your bundle, trickles down through your collections, and ends with the nitty gritty details of your data to provide you with PDS4 labels.</p>
           </div>
           <!--/.Column-->
           <!--Column-->
           <div class="col-md-4">
              
           </div>
           <!--/.Column-->
       </div>
       <!--/.Row-->
       <hr/>
       <!--Row-->
       <div class="row pt-2">
           <!--Column-->
           <div class="col-md-7 push-md-5">
              <p class="lead">
              Sign in below or sign up <a href="{% url 'friends:register' %}">here</a>.
                  <form id="login_form" method="post" action="{% url 'friends:login' %}">
                      {% csrf_token %}
                      Username:  <input type="text" name="username" value="" size="50" /><br />
                      Password:  <input type="password" name="password" value="" size="50"/><br />
                  <input type="submit" value="submit" />
                  </form>
              </p>
          </div>
          <!--/.Column-->
          <!--Column-->
          <div class="col-md-5 pull-md-7">

          </div>
          <!--/.Column-->
      </div>
      <!--/.Row-->
    {% endif %}
{% endblock %}