elsa/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from main import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^accounts/', include('friends.urls')),
    url(r'^context/', include('context.urls')),
    url(r'^build/', include('build.urls')),
    url(r'^review/', include('review.urls')),
    url(r'^tutorial/', include('tutorial.urls')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static(settings.ARCHIVE_URL, document_root=settings.ARCHIVE_DIR)

main/urls.py
"""
K. Sweebe

elsa.main.urls shows the listing of all current urls associated with elsa's main app.

"""

from django.conf.urls import url
from . import views

app_name='main'
urlpatterns = [

    # elsa's main views.
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^services/$', views.services, name='services'),
    url(r'^construction/$', views.construction, name='construction'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^error/$', views.error, name='error'),
    url(r'^restricted_access/$', views.restricted_access, name='restricted_access'),
    url(r'^simple_upload/$', views.simple_upload, name='simple_upload'),

    # I use this for development (k).
    url(r'^success/$', views.success, name='success'),
]

tutorial/urls.py
# Stdlib imports

# Core Django imports
from django.conf.urls import url

# Third-party app imports

# Imports from apps
from . import views

app_name='tutorial'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^build_a_bundle/$', views.build_a_bundle, name='build_a_bundle'),
    url(r'^build_a_bundle/bundle_and_collections/$', views.bundle_and_collections, name='bundle_and_collections'),
    url(r'^build_a_bundle/(?P<pk_bundle>\d+)/collection_context/$', views.collection_context, name='collection_context'),
    url(r'^build_a_bundle/(?P<pk_bundle>\d+)/collection_data/$', views.collection_data, name='collection_data'),
    url(r'^build_a_bundle/(?P<pk_bundle>\d+)/collection_document/$', views.collection_document, name='collection_document'),

]

tutorial/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

tutorial/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from build.forms import *
from build.models import *

# Create your views here.
@login_required
def index(request):
    return render(request, 'tutorial/index.html', {})

@login_required
def build_a_bundle(request):
    return render(request, 'tutorial/introduction_build.html', {})

@login_required
def bundle_and_collections(request):
    print 'DEBUG START --------------------'
    form_bundle = BundleForm(request.POST or None)
    form_collections = CollectionsForm(request.POST or None)
    context_dict = {
        'form_bundle':form_bundle,
        'form_collections':form_collections,
    }

    if form_bundle.is_valid() and form_collections.is_valid():
        print 'all forms valid'

        # Check Uniqueness
        bundle_name = form_bundle.cleaned_data['name']
        bundle_user = request.user
        bundle_count = Bundle.objects.filter(name=bundle_name, user=bundle_user).count()
        # If user and bundle name are unique, then...
        if bundle_count == 0:

            # Build Bundle model object and begin PDS4 Compliant Bundle directory in User Directory.
            # This Bundle Directory will contain a Product_Bundle label.
            bundle = build.Bundle(request, form_bundle)
            
            # Build Collections model object and continue with PDS4 compliant Bundle directory in User 
            # directory.  Bundle directory will contain a collection folder for each collection and a
            # Product_Collection label.            
            build.Collections(request, form_collections, bundle)
            
            # Further develop context_dict entries for templates            
            context_dict['Bundle'] = bundle
            context_dict['Product_Bundle'] = Product_Bundle.objects.get(bundle=bundle)
            context_dict['Product_Collection_Set'] = Product_Collection.objects.filter(bundle=bundle)

            return HttpResponse("Yeah, we're getting here")

    return render(request, 'tutorial/bundle_and_collections.html', context_dict)


@login_required
def collection_context(request, pk_bundle):
    context_dict = {}
    return render(request, 'tutorial/collection_context.html', context_dict)

@login_required
def collection_data(request, pk_bundle):
    context_dict = {}
    return render(request, 'tutorial/collection_data.html', context_dict)


@login_required
def collection_document(request, pk_bundle):
    context_dict = {}
    return render(request, 'tutorial/collection_document.html', context_dict)



def new(request):
    return HttpResponse("Begin Build Tutorial")

templates/tutorial/bundle_and_collections.html
{% extends 'main/base-k.html' %}
{% load static %}




{% block title_block %}
Build A Bundle



{% endblock %}




{% block main_header_block %}
So you want to build a bundle?<br/>
{% endblock %}

{% block about_header_block %}
<p>
A bundle is a list of related collections.  A collection is a list of related basic products.  A basic product is the simplest product in PDS4 and there are two types, observational and non-observational products.  Examples of basic products are Product_Context, Product_Document, Product_XML_Schema, and Product_Observational.  This is not a complete list of PDS4 basic products; however, these products will be discussed within this tutorial.  Aside from basic products, PDS4 has aggregate products.  Product_Bundle and Product_Collection are aggregate products and are the only two products that are not basic products.  Each bundle has exactly one Product_Bundle and each collection has exactly one Product_Collection.  
</p>
<p>
Enter the name of your bundle below and select the appropriate collections that your bundle is composed of.  ELSA then creates the overarching bundle directory structure and begins the Product_Bundle and Product_Collection labels within your bundle. The following steps of this tutorial then go into PDS4's basic products for the document, context, xml_schema, and data collections.
</p>
<p>
For more information, please visit <a href="https://pds.jpl.nasa.gov/pds4/doc/concepts/Concepts_1.9.0.pdf">PDS4 Concepts</a>.
</p>
{% endblock %}



{% block body_block %}
<script src="{% static 'js/build_a_bundle.js' %}" language="Javascript" type="text/javascript"></script>
<!--Third row-->
<div class="row pt-2">
    <!--First column-->
    <div class="col-md-12">
        <h3 class="card-header elegant-color white-text text-center z-depth-2">Provide Bundle Information</h3><br/>
    </div>
    <!--/.First column-->
</div>
<!--/.Third row-->
<!--First row-->
<div class="row pt-2">
    <!--First column-->
    <div class="col-md-6">
        <form method="post">
             {% csrf_token %}
             <div id="">
                 {{ form_bundle.as_p }}
             </div>
             <br/>
             <div id="">
                 Pick and assign collections for your bundle: <br/>
                 {{ form_collections.as_p }}
             </div>
             <br />
 
            <input class="btn btn-default" type="submit" value="Submit" />
        </form>       
    </div>
    <!--/.First column-->
    <!--Second column-->
    <div class="tutorial col-md-6">
        <p>Helloooooo
        </p>
    </div>           
    <!--/.Second column-->
</div>
<!--/.First row-->
{% endblock %}

templates/tutorial/collection_context.html
{% extends 'main/base-k.html' %}
{% load static %}

{% block title_block %}
Collections
{% endblock %}

{% block main_header_block %}
Context Collection
{% endblock %}

{% block about_header_block %}
<p>
Context products reference a physical or conceptual object like a facility (laboratory, observatory, telescope) or mission (instrument, target).  Context products are finalized and managed in a PDS master context bundle so that all data providers can access and use the same material.  The Product_Collection lists each context product associated with the bundle.  Each context product has a Product_Context label that briefly describes the physical or conceptual object.  
</p>
<p>
A bundle is not required to include context products.  ELSA generates the list within the Product_Collection and then a simple text file (?) that lists the lids for each context product. <b>DOUBLE CHECK THIS</b>
</p>
{% endblock %}

{% block body_block %}

{% endblock %}

templates/tutorial/collection_data.html
{% extends 'main/base-k.html' %}
{% load static %}

{% block title_block %}
Collections
{% endblock %}

{% block main_header_block %}
Data Collection
{% endblock %}


{% block about_header_block %}

<p>
The data collection consists of a Product_Collection that lists the data products found in the data collection and a Product_Observational for each data product.  PDS4 uses four fundamental data structures: 
<ol><li>Array (images, spectral cubes)</li><li>Table (binary and/or character fixed-length tables)</li><li>Parsable Byte Stream (text files, XML files, CSV tables)</li><li>Encoded Byte Stream (PDF files, JPEG images) NOTE: Not used for science observations</li></ol>The vast majority of observational data can be described as either N-dimensional arrays or tables.  The type of data structure associated with your bundle is dependent upon the nature of the observational data.  This decision is to be made with your node representative.  To see a list of which subclasses exist for the Product_Observational class visit the <a href="https://pds.jpl.nasa.gov/pds4/doc/dph/current/PDS4_DataProvidersHandbook_1.9.0.pdf">Data Provider's Handbook, 6.2.2.1</a>
</p>
<p>
When a data template is added to a bundle (whether it be 2D Array, Table Character Delimited, etc.), ELSA adds the product to the list in Product_Collection and creates a Product_Observational.  The Product_Observational contains: 
<ul>
    <li>a reference list area for articles and other products relevant to understanding the product</li>
    <li>file area for identifying the file(s) containing the digital object(s) and includes classes that describe each digital object in the given file (e.g., the description and parameters of each header, table, and image).</li>
</ul>

</p>

{% endblock %}


{% block body_block %}

{% endblock %}

templates/tutorial/collection_document.html
{% extends 'main/base-k.html' %}
{% load static %}

{% block title_block %}
Collections
{% endblock %}

{% block main_header_block %}
Document Collection
{% endblock %}


{% block about_header_block %}
<p>
A document is any text-based information supplied to assist the user in understanding, interpreting, calibrating, or otherwise manipulating the data. The document collection contains a Product_Collection label that lists the documents included in the document collection.  Each document in the document collection has a Product_Document label that describes the stated document.
</p>
<p>
For more information, please visit <a href="https://pds.jpl.nasa.gov/pds4/doc/concepts/Concepts_1.9.0.pdf">PDS4 Concepts</a>.
</p>
{% endblock %}

{% block body_block %}

{% endblock %}

templates/tutorial/index.html
{% extends 'main/base-k.html' %}
{% load static %}




{% block title_block %}             Tutorial  {% endblock %}




{% block main_header_block %}       Tutorials  {% endblock %}



{% block body_block %}

<!--First row-->
<div id="row">
    <!--First column-->
    <div class="col-md-6">
        <p>This page contains the following content: 1) beginning of tutorials-build, 2) archives for past posters and good stuff like that, 3)... </p>
    </div>
</div>
<!--/.First row-->
<!--Second row-->
<div id="row">
    <!--First column-->
    <div class="col-md-12"><h3 class="card-header elegant-color white-text text-center z-depth-2">
        How to use ELSA</h3><br/>
    </div>
</div>
<div id="row">
    <!--First column-->
    <div class="col-md-12">
        <ul>
            <li>
                <a href="{% url 'tutorial:build_a_bundle' %}">Build A Bundle Tutorial</a>
            </li>
            <li>
                <a href="{% url 'main:construction' %}">Data Review Tutorial</a>
            <li>
                <a href="{% url 'main:construction' %}">Data Submission Tutorial</a>
            </li>
        </ul>
    </div>
</div>
<!--/.Second row-->

<!--Second row-->
<div id="row">
    <!--First column-->
    <div class="col-md-12"><h3 class="card-header elegant-color white-text text-center z-depth-2">
        ELSA Trainings and Posters</h3><br/>
    </div>
</div>
<div id="row">
    <!--First column-->
    <div class="col-md-12">
        <ul>
            <li>
                <p>Here is a nonexistent list of posters and tutorials</p>
            </li>

        </ul>
    </div>
</div>
<!--/.Second row-->

<!--Optional row-->
<div id="row">
    <!--First column-->
    <div class="col-md-12"><h3 class="card-header elegant-color white-text text-center z-depth-2">
        Historic ELSA Links</h3><br/>
    </div>
</div>
<div id="row">
    <!--First column-->
    <div class="col-md-12">
        <ul>
            <li>
                <a href="http://pds-atmospheres.nmsu.edu/ELSA/tutorial/buildBundle.html">PDS4 Label Tutorial</a>
            </li>
            <li>
                <a href="http://pds-atmospheres.nmsu.edu/ELSA/build/title.html">Build-A-Bundle</a>
</li>
            <li></li>
        </ul>
    </div>
</div>
<!--/.Optional row-->
{% endblock %}

templates/tutorial/introduction_build.html
{% extends 'main/base-k.html' %}
{% load static %}




{% block title_block %}             Tutorial - Build A Bundle  {% endblock %}




{% block main_header_block %}       Build A Bundle Tutorial  {% endblock %}
{% block about_header_block %}

This tutorial covers the base case of building bundles.  The tutorial takes users through a linear progression of the Build A Bundle app.  The user will be required to: <ol><li> create a bundle,</li><li> add collections,</li><li> add a product,</li><li> add instruments and targets,</li><li> and refine the small details within the bundle using the editor.</li></ol>  The intent of this tutorial is not to walk a user through the precise specificity of their bundle; rather, the intent is to give the user a feel for how ELSA works and then from there the user will obtain enough knowledge about the basics.  Seperate tutorials can be created to teach users different parts of ELSA once those parts are built. 

<p>
Graphic here that documents the flow of the tutorial.  We could use this graphic as a pagination type of thing.  So under each section, a bar or checkmark will go off once a user completes a page ?  Think about it.  
</p>
  {% endblock %}



{% block body_block %}
<div id="row">
    <!--First column-->
    <div class="col-md-12">
        <a href="{% url 'tutorial:bundle_and_collections' %}"><button type="button" class="btn btn-default">Begin Tutorial</button></a>        
    </div>

</div>
<!--/.Second row-->

{% endblock %}

templates/tutorial/two.html
{% extends 'main/base-k.html' %}
{% load static %}

{% block title_block %}
Context
{% endblock %}

{% block main_header_block %}
Context Query
{% endblock %}

{% block body_block %}
<!--First row-->
<div class="row pt-2">
    <!--First column-->
    <div class="col-md-12">
        <h4>First ELSA needs to know whether your bundle requires facility information or instrument and target information.  Please click the appropriate button below.</h4>
       
    </div>
    <!--/.First column-->
</div>
<!--/.First row-->
<!--First row-->
<div class="row pt-2">
    <!--First column-->
    <div class="col-md-4">
        <a href="{% url 'build:context_search_facility' bundle.pk %}">
            <button type="button" class="btn btn-default" id="facility">Facility</button>
        </a>
        <a href="{% url 'build:context_search' bundle.pk %}">
            <button type="button" class="btn btn-default" id="mission">Mission</button>
        </a>
    </div>
    <!--/.First column-->
    <!--Second column-->
    <div class="col-md-8 help">
    </div>
    <!--/.Second column-->
</div>
<!--/.First row-->
<hr/>
<!--Second row-->
<div class="row pt-2">
    <!--First column-->
    <div class="col-md-12">
        <h3 class="card-header elegant-color white-text text-center z-depth-2">Current Instruments</h3>
    </div>
    <!--/.First column-->
</div>
<!--/.Second row-->
<!--Third row-->
<div class="row pt-2">
{% if instrument_list %}    
    {% for instrument in instrument_list %}

    <!--Column-->
    <div class="col-md-3">
        <!--Card-->
        <div class="card">
            <!--Card image-->
            <img class="img-fluid" src="{% static 'images/warp_zone.svg' %}" alt="Instrument Image">
            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <h4 class="card-title">{{ instrument }}</h4>
                <!--Text-->
                <p class="card-text">{{ instrument.lid }}</p>
                <!--Buttons-->
                <a href="{% url 'main:construction' %}">
                    <button type="button" class="btn btn-danger">Remove</button> 
                </a>
            </div>
        </div>
        <!--/.Card-->
    </div>
    <!--/.Column-->
    {% endfor %}
{% else %}
    <!--Column-->
    <div class="col-md-3">
        <!--Card-->
        <div class="card">
            <!--Card image-->
            <img class="img-fluid" src="{% static 'images/null.png' %}" alt="Instrument Image">
            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <h4 class="card-title">Null</h4>
                <!--Text-->
                <p class="card-text">No instruments are associated with {{ bundle }}.</p>
            </div>
        </div>
        <!--/.Card-->
    </div>
    <!--/.Column-->
{% endif %}
</div>
<!--/.Third row-->
<hr/>
<!--Second row-->
<div class="row pt-2">
    <!--First column-->
    <div class="col-md-12">
        <h3 class="card-header elegant-color white-text text-center z-depth-2">Current Targets</h3>
    </div>
    <!--/.First column-->
</div>
<!--/.Second row-->
<!--Third row-->
<div class="row pt-2">
{% if target_list %}    
    {% for target in target_list %}
    
    <!--Column-->
    <div class="col-md-3">
        <!--Card-->
        <div class="card">
            <!--Card image-->
            <img class="img-fluid" src="{% static 'images/target.jpg' %}" alt="Target Image">
            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <h4 class="card-title">{{ target }}</h4>
                <!--Text-->
                <p class="card-text">{{ target.lid }}</p>
                <!--Buttons-->
                <a href="{% url 'main:construction' %}">
                    <button type="button" class="btn btn-danger">Remove</button> 
                </a>
            </div>
        </div>
        <!--/.Card-->
    </div>
    <!--/.Column-->

    {% endfor %}
{% else %}
    <!--First column-->
    <div class="col-md-3">
        <!--Card-->
        <div class="card">
            <!--Card image-->
            <img class="img-fluid" src="{% static 'images/null.png' %}" alt="An image representing building a label.">
            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <h4 class="card-title">Null</h4>
                <!--Text-->
                <p class="card-text">No targets have been added</p>
            </div>        
        </div>
        <!--/.Card-->
    </div>
    <!--/.First column-->
{% endif %}
    
</div>
<!--/.Third row-->
{% endblock %}